### ISSUE TITLE
beets trying to rename all artists to None

### ISSUE THREAD

**Issue by noahsager** [snejus/beets-bandcamp#7]
I'm noticing that when importing a Bandcamp album with beetcamp, beets wants to rename all artists to None. For example:

```
/Users/noah/Music/beets Import/WYS  - Halloween Night FLAC (15 items)
Correcting tags from:
    WYS - Halloween Night
To:
    None - Halloween Night
URL:
    https://jazzhopcafe.bandcamp.com/album/halloween-night
(Similarity: 91.9%) (artist) (bandcamp, Digital Media, 2020, GB, The Jazz Hop Café)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
```

**Comment by snejus** [comment]
I can tell you have a rather significant music collection there :) Let me investigate this one, haven't seen it before!

**Comment by snejus** [comment]
Hm, interesting, I'm seeing this: 

```
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, Print tracks, eDit, edit Candidates? 1
Correcting tags from:
    (unknown album)
To:
    WYS - Halloween Night
URL:
    https://jazzhopcafe.bandcamp.com/album/halloween-night
(Similarity: 3.9%) (missing tracks, album, artist, tracks) (bandcamp, Digital Media, 2020, GB, The Jazz Hop Café)
 * WYS - Hazelnut Soup.mp3 (#0) -> Hazelnut Soup (#5) (title)
Missing tracks (14/15 - 93.3%):
 ! The Mansion          (# 1) (2:37)
 ! Black Rose           (# 2) (2:46)
 ! Elixir               (# 3) (2:19)
 ! The Butler IV        (# 4) (2:24)
 ! Splinter Woods       (# 6) (2:46)
 ! Charlie and Molly    (# 7) (3:16)
 ! The Widow's Lament   (# 8) (3:11)
 ! Rosewell             (# 9) (2:44)
 ! Deadly Nightshade    (#10) (1:36)
 ! Monsieur Loyal       (#11) (2:27)
 ! The Elevator's Ghost (#12) (2:18)
 ! Plasma               (#13) (2:07)
 ! Lily Tornthorns      (#14) (3:02)
 ! Exit The Mansion     (#15) (4:16)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, Print tracks, eDit, edit Candidates?  
```

I `ytdl`-ed one of the album tunes to check it, and it seems like it did it correctly. Once I imported it, I found:
```
               added: 2021-01-19 01:00
               album: Halloween Night
            album_id: 186
         albumartist: WYS
         albumstatus: Official
          albumtotal: 15
           albumtype: album
              artist: WYS
             artpath: None
            bitdepth: 0
             bitrate: 128kbps
                 bpm: 0
            channels: 2
                comp: False
             country: GB
         data_source: bandcamp
                 day: 08
                disc: 01
           disctotal: 01
            filesize: 1854754
              format: MP3
               genre: Lo-Fi
                  id: 1212
               label: The Jazz Hop Café
              length: 1:55
    mb_albumartistid: https://jazzhopcafe.bandcamp.com
          mb_albumid: https://jazzhopcafe.bandcamp.com/album/halloween-night
         mb_artistid: https://jazzhopcafe.bandcamp.com
          mb_trackid: https://jazzhopcafe.bandcamp.com/track/hazelnut-soup
               media: Digital Media
             missing: 14
               month: 10
               mtime: 2021-01-19 01:00
        original_day: 00
      original_month: 00
       original_year: 0000
     r128_album_gain: 000000
     r128_track_gain: 000000
       rg_album_gain: 0.0
       rg_album_peak: 0.0
       rg_track_gain: 0.0
       rg_track_peak: 0.0
          samplerate: 44kHz
           singleton: False
               title: Hazelnut Soup
               track: 05
          tracktotal: 15
                year: 2020
              ```

Hmm I wonder which setting could this be related to.

**Comment by noahsager** [comment]
Weird. What utility did you use to print the tags? I could run it on my original if that'd be helpful.

**Comment by noahsager** [comment]
Here's my config file. I'm pretty stock:

```
directory: /Volumes/Music
library: ~/Music/beetsdatabase.db
import:
    log: /Users/noah/Desktop/beetsimport.txt
    move: true
plugins: bandcamp edit fetchart
bandcamp:
    lyrics: true
    art: true
```

**Comment by snejus** [comment]
> Weird. What utility did you use to print the tags? I could run it on my original if that'd be helpful.

Yes please, that may shed some more light onto this! That's the internal `info` plugin - it should be enough to just include it in your plugins list.

**Comment by noahsager** [comment]
```
   ~  beet info /Users/noah/Downloads/WYS\ \ -\ Halloween\ Night\ FLAC/01\ -\ The\ Mansion.flac                
/Users/noah/Downloads/WYS  - Halloween Night FLAC/01 - The Mansion.flac
      album: Halloween Night
albumartist: WYS
        art: True
     artist: WYS
   bitdepth: 16
    bitrate: 697891
   channels: 2
   comments: Visit https://jazzhopcafe.bandcamp.com
       date: 2020-01-01
     format: FLAC
     genres: 
     length: 157.0468707482993
 samplerate: 44100
      title: The Mansion
      track: 1
       year: 2020
```

**Comment by snejus** [comment]
I've tried using your config and setting the same metadata on the tracks and failed reproduce it. Just so that we're on the same page, which version are you running?

**Comment by arogl** [comment]
Seeing the same issue:

```
/mnt/i/musica/A/Alison Avron/(2013) Alison Avron Live at The Newsagency (9 items)
Correcting tags from:
    Alison Avron - Alison Avron Live at The Newsagency
To:
    None - Alison Avron Live at The Newsagency
URL:
    https://alisonavron.bandcamp.com/album/alison-avron-live-at-the-newsagency
(Similarity: 88.5%) (artist, country) (bandcamp, Digital Media, 2013, AU, Alison Avron)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? s

/mnt/i/musica/A/Alison Avron/(2013) By Your Side (4 items)
Correcting tags from:
    Alison Avron - By Your Side
To:
    None - By Your Side
URL:
    https://alisonavron.bandcamp.com/album/by-your-side
(Similarity: 82.9%) (artist, country) (bandcamp, Digital Media, 2013, AU, Alison Avron)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? b
```

```
beetcamp V0.5.5
beets commit 04ea754d00e2873ae9aa2d9e07c5cefd790eaee2 (HEAD -> master, origin/master, origin/HEAD)
```

Beet config for bandcamp
``` yaml
bandcamp:
    art: true
    lyrics: true
```
